id = "test"
worker_pool_size = 3
jobs = [
{path_to_cmd = "./spark-stream.sh", number_of_jobs = 1},
{path_to_cmd = "./spark-ml.sh",     number_of_jobs = 1},
{path_to_cmd = "./spark-batch.sh",  number_of_jobs = 1}
]
